config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # resources :posts, only: [:new], as: 'new_post'
  root to: "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:new, :create, :show, :index, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end

  namespace :api, :defaults => {:format => :json}  do
    resources :users do
      resources :posts, only: [:index, :show, :create, :destroy] do
        resources :comments, only: [:index, :show, :create, :destroy]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post, public: true
    can :read, Comment, public: true

    # additional permissions for logged in users (they can read their own posts)
    return unless user.present?

    can(:read, Post, user:)
    can :destroy, Post.where(author_id: user.id)

    can(:read, Comment, user:)
    can :destroy, Comment.where(author_id: user.id)

    return unless user.role == 'admin' # additional permissions for administrators

    can :manage, :all
    can :destroy, Post
    can :destroy, Comment
  end
end
# initial ability class used but not working
# class Ability
#   include CanCan::Ability

#   def initialize(user)
#     if user.role == 'admin'
#       can :manage, :all
#     else
#       can :manage, Post, author: user
#       can :manage, Comment, author: user
#       can :read, :all
#     end
#   end
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comment_counter
  after_destroy :update_comment_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_like_counter
  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_count
  after_destroy :update_post_counter

  def update_post_count
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @user = User.find(params[:user_id])
    # @user =current_user
    @post = @user.posts.find(params[:post_id])
    @comments = @post.comments
    render json: @comments
  end

  def create
    # no need to initialise user for now as user_id will be passed in the body to ensure
    # that the user making the request is the author bcos no login yet so it can't pick up the id from the params.

    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { error: @comment.errors.full_messages.join(', ') }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :author_id)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    render json: @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
  # this is for when we had to create the current_user method in the application controller
  # def current_user
  #   @current_user = User.first
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.author_id = current_user.id

    if @comment.save
      redirect_to users_path, notice: 'Comment was successfully created.'
    else
      render 'posts#show'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to user_post_path(@post), notice: 'Comment was successfully deleted.'
  end

  private

  def set_current_user
    @current_user = current_user
  end

  def comment_params
    params.permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def new
    @like = Like.new
  end

  def create
    @like = Like.new(like_params)
    @like.post_id = params[:post_id]
    @like.author_id = current_user.id

    if @like.save
      redirect_to users_path, notice: 'Like was successfully created.'
    else
      render 'posts#show'
    end
  end

  private

  def set_current_user
    @current_user = current_user
  end

  def like_params
    params.permit(:text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  # load_and_authorize_resource
  # before_action :set_current_user

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author, comments: :author)
  end

  def show
    @post = Post.find_by(id: params[:id])
    # @user = current_user
    @user = User.find(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    # this is for when we had the current_user method in the application controller
    # or when the confirmable has been correctly setup so the current_user will have a value
    # @user = current_user

    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)

    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to user_posts_path(@post.author_id), notice: 'Post was successfully deleted.'
    else
      flash.now[:errors] = @post.errors.full_messages
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  # def set_current_user
  #   @current_user = current_user
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @users = User.all
    @users = User.includes(:posts)
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_new_comment.html.erb
<div class="flex flex-col">
  <%= form_with(model: @comment, url: user_post_comments_path(post_id: @post.id, user_id: @user.id), local: true )  do |form| %>


    <%= form.label :text %>
    <%= form.text_field :text %>

    <%= form.submit "Create Comment" %>
    <% end %>
</div

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="p-4">
      <div class="flex flex-row justify-center items-center">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/likes/_new_like.html.erb
<%= form_with(model: @like, url: user_post_likes_path(post_id: post.id, user_id: user.id), local: true) do |form| %>
    <%= form.submit "Like" %>
  <% end %>

app/views/posts/index.html.erb
  <div class="flex flex-row py-5 gap-5">
    <div class="border border-black w-1/6 h-20">
        <img src=<%= @user.photo %> alt="profile">
    </div>
    <div class = "border rounded border-black flex flex-row p-3 justify-between w-5/6">
      <h1><%= @user.name%></h1>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <% @posts.each_with_index do |post, index| %>
    <div>
      <div class = "border rounded border-black flex flex-col p-2 gap-3">
        <h3 class = "p-0 hover:bg-blue-700"><%= link_to "Post ##{index +1}", user_post_path(@user, post) %></h1>
        <p><%= post.title %></p>
        <p><%= post.text %></p>
        <p> Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %> </p>
      </div>
      <div class = "border rounded border-black flex flex-col p-2 gap-3">
        <% post.recent_comments.each do | comment| %>
          <div >
            <p><%= comment.author.name%>:<%= comment.text %></p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <button class = "border rounded border-black p-2 my-4">Pagination</button>
  <button class = "border rounded border-black p-2 my-4"><%= link_to 'Create new post', new_user_post_path%></button>

app/views/posts/new.html.erb
<h1>Create a New Post</h1>

<%= form_with(model: @post, url: user_posts_path(user_id: params[:user_id] ), local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :text %>
  <%= form.text_area :text %>

  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<div  class = "border rounded border-black flex flex-col p-2 gap-3">
  <ul  class = "flex flex-row p-2 gap-3 justify-between">
    <h1><%= @post.title%> by <%= @user.name%> </h1>
    <p>Comments: <%= @post.comments_counter%>, Likes: <%= @post.likes_counter%></p>
  </ul>
  <p> <%= @post.text %></p>
</div>
<div  class = "border rounded border-black flex flex-col p-2 gap-3">
  <% @post.recent_comments.each do |comment| %>
    <div>
      <p><%=comment.author.name %>: <%=comment.text %></p>
    </div>
    <% if can? :destroy, comment %>
      <%= button_to 'Delete Comment', user_post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
    <% end %>
  <% end %>
</div>
<% if can? :destroy, @post %>
  <%= button_to 'Delete Post', user_post_path(@user, @post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %>
<% end %>
<div class = "border rounded border-black flex flex-col p-2 gap-3">
    <%= render partial: 'comments/new_comment', locals: { post: @post, user: @user, user_id: params[:user_id] } %>
</div>
<div  class = "border rounded border-black flex flex-col p-2 gap-3">
  <%= render partial: 'likes/new_like', locals: { post: @post, user: @user, user_id: params[:user_id] } %>
</div

app/views/users/index.html.erb
<% if @users.blank? %>
  <p>There are no users yet.</p>
  <button class= "rounded border-2 p-2 mt-4">
    <%= link_to "Sign In", new_user_session_path %>
  </button>

<%else%>
  <ul class="flex flex-col p-5">
  <% @users.each do |user| %>
    <div class="flex flex-row p-5 gap-5">
      <div class="border border-black w-1/6 h-20">
        <img src=<%= user.photo %> alt="profile">
      </div>
      <div class = "border rounded border-black flex flex-row p-3 justify-between w-5/6">
        <h1 class="hover:bg-blue-700 "><%= link_to user.name, user_path(user.id) %></h1>
        <p>Number of posts: <%= user.posts_counter %></p>
      </div>
    </div>
  <% end %>
  </ul>
<% end %>

app/views/users/show.html.erb
<div class="flex flex-row py-5 gap-5">
  <div class="border border-black w-1/6 h-20">
        <img src=<%= @user.photo %> alt="trial">
  </div>
  <div class = "border rounded border-black flex flex-row p-3 justify-between w-5/6">
    <h1><%= @user.name %></h1>
    <p>Number of posts: <%= @user.posts_counter %></p>
  </div>
</div>
<div class = "border rounded border-black flex flex-col p-2 gap-3">
  <p>Bio</p>
  <p><%= @user.bio %></p>
</div>

  <div>
    <% @user.recent_posts.each_with_index do |post, index| %>
        <div class="border rounded border-black flex flex-col mt-3 p-3 gap-5">
          <button class="p-0 hover:bg-blue-700"><%= link_to "Post ##{index +1}", user_posts_path(@user) %></button>
          <p><%= post.text %></p>
          <p>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
        </div>
    <% end %>
  </div>
  <button class = "border rounded border-black p-2 my-4"><%= link_to 'Create new post', new_user_post_path(@user)%></button>
  <button class = "border rounded border-black my-4"> <%=link_to 'See all posts', users_path%></button>